#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/motorola/borneo

PRODUCT_PACKAGES += \
    CarrierConfigOverlay

PRODUCT_COPY_FILES += \
    vendor/motorola/borneo/proprietary/product/etc/CarrierSettings/carrier_list.pb:$(TARGET_COPY_OUT_PRODUCT)/etc/CarrierSettings/carrier_list.pb \
    vendor/motorola/borneo/proprietary/product/etc/CarrierSettings/others.pb:$(TARGET_COPY_OUT_PRODUCT)/etc/CarrierSettings/others.pb

PRODUCT_COPY_FILES += \
    vendor/motorola/borneo/proprietary/recovery/root/vendor/firmware/FT8006U_Pramboot.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/FT8006U_Pramboot.bin \
    vendor/motorola/borneo/proprietary/recovery/root/vendor/firmware/NT36xxx_MP_Setting_Criteria_601E.csv:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/NT36xxx_MP_Setting_Criteria_601E.csv \
    vendor/motorola/borneo/proprietary/recovery/root/vendor/firmware/djn_novatek_ts_fw.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/djn_novatek_ts_fw.bin \
    vendor/motorola/borneo/proprietary/recovery/root/vendor/firmware/djn_novatek_ts_mp.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/djn_novatek_ts_mp.bin \
    vendor/motorola/borneo/proprietary/recovery/root/vendor/firmware/focaltech_ts_fw_djnboe.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/focaltech_ts_fw_djnboe.bin \
    vendor/motorola/borneo/proprietary/recovery/root/vendor/firmware/ilitek_fw.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/ilitek_fw.bin \
    vendor/motorola/borneo/proprietary/vendor/etc/acdbdata/Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Bluetooth_cal.acdb \
    vendor/motorola/borneo/proprietary/vendor/etc/acdbdata/General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/General_cal.acdb \
    vendor/motorola/borneo/proprietary/vendor/etc/acdbdata/Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Global_cal.acdb \
    vendor/motorola/borneo/proprietary/vendor/etc/acdbdata/Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Handset_cal.acdb \
    vendor/motorola/borneo/proprietary/vendor/etc/acdbdata/Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Hdmi_cal.acdb \
    vendor/motorola/borneo/proprietary/vendor/etc/acdbdata/Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Headset_cal.acdb \
    vendor/motorola/borneo/proprietary/vendor/etc/acdbdata/Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Speaker_cal.acdb \
    vendor/motorola/borneo/proprietary/vendor/etc/acdbdata/adsp_avs_config.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/adsp_avs_config.acdb \
    vendor/motorola/borneo/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__2.0.0_0.1__3.0.0_0.0__eai_1.00.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__2.0.0_0.1__3.0.0_0.0__eai_1.00.pmd \
    vendor/motorola/borneo/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__2.2.0_0.1__3.0.0_0.0__eai_1.00.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__2.2.0_0.1__3.0.0_0.0__eai_1.00.pmd \
    vendor/motorola/borneo/proprietary/vendor/etc/acdbdata/nn_vad_models/fai_3.0.0_0.0_eai_1.00.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_vad_models/fai_3.0.0_0.0_eai_1.00.pmd \
    vendor/motorola/borneo/proprietary/vendor/etc/camera/dual_golden_depth.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/dual_golden_depth.bin \
    vendor/motorola/borneo/proprietary/vendor/etc/camera/vidhance_calibration:$(TARGET_COPY_OUT_VENDOR)/etc/camera/vidhance_calibration \
    vendor/motorola/borneo/proprietary/vendor/etc/init/android.hardware.biometrics.fingerprint@2.1-service-ets2.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.biometrics.fingerprint@2.1-service-ets2.rc \
    vendor/motorola/borneo/proprietary/vendor/etc/init/android.hardware.biometrics.fingerprint@2.1-service-fpc2.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.biometrics.fingerprint@2.1-service-fpc2.rc \
    vendor/motorola/borneo/proprietary/vendor/etc/init/init.ets.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.ets.rc \
    vendor/motorola/borneo/proprietary/vendor/etc/init/init_thermal-engine.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init_thermal-engine.rc \
    vendor/motorola/borneo/proprietary/vendor/etc/qdcm_calib_data_mipi_mot_vid_djn_720p_655.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_mipi_mot_vid_djn_720p_655.xml \
    vendor/motorola/borneo/proprietary/vendor/etc/qdcm_calib_data_mipi_mot_vid_djnboe_720p_655.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_mipi_mot_vid_djnboe_720p_655.xml \
    vendor/motorola/borneo/proprietary/vendor/etc/qdcm_calib_data_mipi_mot_vid_tm_720p_655.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_mipi_mot_vid_tm_720p_655.xml \
    vendor/motorola/borneo/proprietary/vendor/etc/sensors/config/bengal_power_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/bengal_power_0.json \
    vendor/motorola/borneo/proprietary/vendor/etc/sensors/config/borneo_ak991x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/borneo_ak991x_0.json \
    vendor/motorola/borneo/proprietary/vendor/etc/sensors/config/borneo_ak991x_0_dvt1.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/borneo_ak991x_0_dvt1.json \
    vendor/motorola/borneo/proprietary/vendor/etc/sensors/config/borneo_bmp380_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/borneo_bmp380_0.json \
    vendor/motorola/borneo/proprietary/vendor/etc/sensors/config/borneo_icm4x6xx_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/borneo_icm4x6xx_0.json \
    vendor/motorola/borneo/proprietary/vendor/etc/sensors/config/borneo_icp101xx_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/borneo_icp101xx_0.json \
    vendor/motorola/borneo/proprietary/vendor/etc/sensors/config/borneo_lsm6dso_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/borneo_lsm6dso_0.json \
    vendor/motorola/borneo/proprietary/vendor/etc/sensors/config/borneo_mmc5603x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/borneo_mmc5603x_0.json \
    vendor/motorola/borneo/proprietary/vendor/etc/sensors/config/borneo_mmc5603x_0_dvt1.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/borneo_mmc5603x_0_dvt1.json \
    vendor/motorola/borneo/proprietary/vendor/etc/sensors/config/borneo_tmd2755_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/borneo_tmd2755_0.json \
    vendor/motorola/borneo/proprietary/vendor/etc/sensors/config/borneo_tmd2755_0_dvt1.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/borneo_tmd2755_0_dvt1.json \
    vendor/motorola/borneo/proprietary/vendor/etc/sensors/config/icm4x6xx_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/icm4x6xx_0.json \
    vendor/motorola/borneo/proprietary/vendor/etc/sensors/config/icp101xx_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/icp101xx_0.json \
    vendor/motorola/borneo/proprietary/vendor/etc/sensors/config/mmc5603x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/mmc5603x_0.json \
    vendor/motorola/borneo/proprietary/vendor/etc/sensors/config/mot_camgest.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/mot_camgest.json \
    vendor/motorola/borneo/proprietary/vendor/etc/sensors/config/mot_chopchop.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/mot_chopchop.json \
    vendor/motorola/borneo/proprietary/vendor/etc/sensors/config/mot_devorient.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/mot_devorient.json \
    vendor/motorola/borneo/proprietary/vendor/etc/sensors/config/mot_drop.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/mot_drop.json \
    vendor/motorola/borneo/proprietary/vendor/etc/sensors/config/mot_ltv.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/mot_ltv.json \
    vendor/motorola/borneo/proprietary/vendor/etc/sensors/config/mot_offbody.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/mot_offbody.json \
    vendor/motorola/borneo/proprietary/vendor/etc/sensors/config/sns_amd.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_amd.json \
    vendor/motorola/borneo/proprietary/vendor/etc/sensors/config/sns_amd_sw_disabled.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_amd_sw_disabled.json \
    vendor/motorola/borneo/proprietary/vendor/etc/sensors/config/sns_amd_sw_enabled.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_amd_sw_enabled.json \
    vendor/motorola/borneo/proprietary/vendor/etc/sensors/config/sns_cm.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_cm.json \
    vendor/motorola/borneo/proprietary/vendor/etc/sensors/config/sns_dae.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_dae.json \
    vendor/motorola/borneo/proprietary/vendor/etc/sensors/config/sns_diag_filter.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_diag_filter.json \
    vendor/motorola/borneo/proprietary/vendor/etc/sensors/config/sns_gyro_cal.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_gyro_cal.json \
    vendor/motorola/borneo/proprietary/vendor/etc/sensors/config/sns_mag_cal.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_mag_cal.json \
    vendor/motorola/borneo/proprietary/vendor/etc/sensors/config/sns_mag_cal_legacy.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_mag_cal_legacy.json \
    vendor/motorola/borneo/proprietary/vendor/etc/sensors/config/sns_pedometer.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_pedometer.json \
    vendor/motorola/borneo/proprietary/vendor/etc/sensors/config/sns_smd.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_smd.json \
    vendor/motorola/borneo/proprietary/vendor/etc/sensors/config/tmd2755_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/tmd2755_0.json \
    vendor/motorola/borneo/proprietary/vendor/etc/sensors/sns_reg_config:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/sns_reg_config \
    vendor/motorola/borneo/proprietary/vendor/etc/thermal-engine-borneo.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine-borneo.conf \
    vendor/motorola/borneo/proprietary/vendor/etc/thermal-engine.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine.conf \
    vendor/motorola/borneo/proprietary/vendor/etc/vhw.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vhw.xml \
    vendor/motorola/borneo/proprietary/vendor/firmware/AbovCapSense.BIN:$(TARGET_COPY_OUT_VENDOR)/firmware/AbovCapSense.BIN \
    vendor/motorola/borneo/proprietary/vendor/firmware/AbovCapSense_4.BIN:$(TARGET_COPY_OUT_VENDOR)/firmware/AbovCapSense_4.BIN \
    vendor/motorola/borneo/proprietary/vendor/firmware/FT8006U_Pramboot.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/FT8006U_Pramboot.bin \
    vendor/motorola/borneo/proprietary/vendor/firmware/NT36xxx_MP_Setting_Criteria_601E.csv:$(TARGET_COPY_OUT_VENDOR)/firmware/NT36xxx_MP_Setting_Criteria_601E.csv \
    vendor/motorola/borneo/proprietary/vendor/firmware/a630_sqe.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a630_sqe.fw \
    vendor/motorola/borneo/proprietary/vendor/firmware/aw882xx_mono.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw882xx_mono.bin \
    vendor/motorola/borneo/proprietary/vendor/firmware/aw882xx_spk_reg.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw882xx_spk_reg.bin \
    vendor/motorola/borneo/proprietary/vendor/firmware/djn_novatek_ts_fw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/djn_novatek_ts_fw.bin \
    vendor/motorola/borneo/proprietary/vendor/firmware/djn_novatek_ts_mp.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/djn_novatek_ts_mp.bin \
    vendor/motorola/borneo/proprietary/vendor/firmware/focaltech_ts_fw_djnboe.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/focaltech_ts_fw_djnboe.bin \
    vendor/motorola/borneo/proprietary/vendor/firmware/ilitek_fw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/ilitek_fw.bin \
    vendor/motorola/borneo/proprietary/vendor/lib64/camera/com.qti.sensormodule.mot_borneo_ov02b10_ofilm.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.mot_borneo_ov02b10_ofilm.bin \
    vendor/motorola/borneo/proprietary/vendor/lib64/camera/com.qti.sensormodule.mot_borneo_ov02b1b_ofilm.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.mot_borneo_ov02b1b_ofilm.bin \
    vendor/motorola/borneo/proprietary/vendor/lib64/camera/com.qti.sensormodule.mot_borneo_s5k4h7_ofilm.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.mot_borneo_s5k4h7_ofilm.bin \
    vendor/motorola/borneo/proprietary/vendor/lib64/camera/com.qti.sensormodule.mot_borneo_s5kgm1st_ofilm.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.mot_borneo_s5kgm1st_ofilm.bin \
    vendor/motorola/borneo/proprietary/vendor/lib64/camera/com.qti.tuned.default.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.default.bin \
    vendor/motorola/borneo/proprietary/vendor/lib64/camera/com.qti.tuned.mot_borneo_ov02b10.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.mot_borneo_ov02b10.bin \
    vendor/motorola/borneo/proprietary/vendor/lib64/camera/com.qti.tuned.mot_borneo_ov02b1b.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.mot_borneo_ov02b1b.bin \
    vendor/motorola/borneo/proprietary/vendor/lib64/camera/com.qti.tuned.mot_borneo_s5k4h7.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.mot_borneo_s5k4h7.bin \
    vendor/motorola/borneo/proprietary/vendor/lib64/camera/com.qti.tuned.mot_borneo_s5kgm1st.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.mot_borneo_s5kgm1st.bin \
    vendor/motorola/borneo/proprietary/vendor/lib64/camera/fdconfigpreview.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/fdconfigpreview.bin \
    vendor/motorola/borneo/proprietary/vendor/lib64/camera/fdconfigpreviewlite.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/fdconfigpreviewlite.bin \
    vendor/motorola/borneo/proprietary/vendor/lib64/camera/fdconfigvideo.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/fdconfigvideo.bin \
    vendor/motorola/borneo/proprietary/vendor/lib64/camera/fdconfigvideolite.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/fdconfigvideolite.bin

PRODUCT_PACKAGES += \
    libthermalclient \
    com.mot.eeprom.mot_dw9767_s5kgm1st_eeprom \
    com.mot.eeprom.mot_gt24p64b_ov02b10_eeprom \
    com.mot.eeprom.mot_ov02b1b_otp \
    com.mot.eeprom.mot_s5k4h7_otp_eeprom \
    com.qti.sensor.mot_ov02b10 \
    com.qti.sensor.mot_ov02b1b \
    com.qti.sensor.mot_s5k4h7 \
    com.qti.sensor.mot_s5kgm1st \
    com.qti.camx.chiiqutils \
    com.qti.eisv2 \
    com.qti.eisv3 \
    com.qti.hvx.addconstant \
    com.qti.hvx.binning \
    com.qti.node.customhwnode \
    com.qti.node.depth \
    com.qti.node.dewarp \
    com.qti.node.dummyrtb \
    com.qti.node.dummysat \
    com.qti.node.eisv2 \
    com.qti.node.eisv3 \
    com.qti.node.fcv \
    com.qti.node.gpu \
    com.qti.node.memcpy \
    com.qti.node.remosaic \
    com.qti.node.stich \
    com.qti.node.swaidenoiser \
    com.qti.node.swcac \
    com.qti.node.swlsc \
    com.qti.node.swmctf \
    com.qti.node.swmfnr \
    com.qti.node.swregistration \
    com.qti.stats.aec \
    com.qti.stats.aecwrapper \
    com.qti.stats.af \
    com.qti.stats.afd \
    com.qti.stats.afwrapper \
    com.qti.stats.asd \
    com.qti.stats.awb \
    com.qti.stats.awbwrapper \
    com.qti.stats.haf \
    com.qti.stats.hafoverride \
    com.qti.stats.pdlib \
    com.qti.stats.pdlibsony \
    com.qti.stats.pdlibwrapper \
    com.qti.stats.tracker \
    com.qtistatic.stats.aec \
    com.qtistatic.stats.af \
    com.qtistatic.stats.awb \
    com.qtistatic.stats.pdlib \
    com.vidhance.node.processing \
    com.vidhance.stats.aec_dmbr \
    com.fingerprints.extension@1.0 \
    com.qti.chiusecaseselector \
    com.qti.feature2.anchorsync \
    com.qti.feature2.demux \
    com.qti.feature2.frameselect \
    com.qti.feature2.fusion \
    com.qti.feature2.generic \
    com.qti.feature2.gs \
    com.qti.feature2.hdr \
    com.qti.feature2.memcpy \
    com.qti.feature2.mfsr \
    com.qti.feature2.qcfa \
    com.qti.feature2.rawhdr \
    com.qti.feature2.rt \
    com.qti.feature2.serializer \
    com.qti.feature2.stub \
    com.qti.feature2.swmf \
    camera.qcom \
    com.qti.chi.override \
    libbitmlengine \
    libcamera_nn_stub \
    libcamerapostproc \
    libcamxexternalformatutils \
    libcamxfacialfeatures \
    libcamxfdalgo \
    libcamxfdengine \
    libcamxifestriping \
    libcamximageformatutils \
    libcamxncs \
    libcamxstatscore \
    libcamxswispiqmodule \
    libcamxswprocessalgo \
    libcamxtintlessalgo \
    libchilog \
    libcom.qti.chinodeutils \
    libets_fp_et5 \
    libets_teeclient \
    libfcell \
    libipebpsstriping \
    libjpege \
    liblmutils-ns \
    liblowlight_ai_portrait.arcsoft \
    libmctfengine_stub \
    libmmcamera_cac3 \
    libmmcamera_faceproc \
    libmmcamera_faceproc2 \
    libmmcamera_lscv35 \
    libmmcamera_mfnr \
    libmmcamera_mfnr_t4 \
    libmot_afd \
    libmot_lux_standardization \
    libofflinelog \
    libopencv \
    libopestriping \
    libswregistrationalgo \
    libtfestriping \
    libvidhance \
    vendor.egistec.hardware.fingerprint@2.0 \
    cnss-daemon \
    android.hardware.biometrics.fingerprint@2.1-service-ets \
    android.hardware.biometrics.fingerprint@2.1-service-fpc \
    fpc_ident \
    thermal-engine
